feat/header
anhnn2401/bai-tap_2 pull request #1
Opened 2020-05-07 04:22 UTC by anhnn2401

2020-05-07 05:06 UTC, sangtx requested changes

2020-05-07 05:06 UTC, txsang commented on src/index.html
> +      <a href="#homepage" alt="home">
Tag a không có attr alt em nhé https://www.w3schools.com/tags/tag_a.asp#table1

2020-05-07 05:06 UTC, txsang commented on src/index.html
> +        <li><a class="munua" href="#homepage">homepage</a></li>
class `munua` có ý nghĩa gì k em?

2020-05-07 05:06 UTC, txsang commented on src/styles/layout/_header.scss
> +  display: flex;
sử dụng @include đối với flex box

2020-05-07 05:06 UTC, txsang commented on src/styles/layout/_header.scss
> +    .ulmenu li {
không style lên thẻ

2020-05-07 06:18 UTC, anhnn2401 commented on src/index.html
> +      <a href="#homepage" alt="home">
dạ a,

2020-05-07 08:27 UTC, sangtx submitted a review, later dismissed

2020-05-07 08:27 UTC, txsang commented on src/index.html
> +      <ul class="ulmenu" id="idulmenu">
sau chỗ này em dùng các class như vầy nè: `list-menu`, `menu-item`, `item-link`

2020-05-07 08:27 UTC, txsang commented on src/scripts/script.js
> +  var x = document.getElementById("idulmenu");
update tên biến `x` về 1 biến có ý nghĩa.

2020-05-07 08:27 UTC, txsang commented on src/styles/layout/_header.scss
> +          margin: 5px 5px;
5px 5px => 5px

2020-05-11 07:27 UTC, sangtx requested changes

2020-05-11 07:27 UTC, sangtx commented on src/scripts/script.js
> +    btnmenu.className += " responsive-menu";
toggleClass('open')

2020-05-11 07:27 UTC, sangtx commented on src/index.html
> +      <a href="javascript:void(0);" class="menu-item" onclick="myFunction()">☰</a>
`menu-item` button class = btn-toggle-menu

2020-05-11 07:27 UTC, sangtx commented on src/scripts/script.js
> +function myFunction() {
$('.btn-toggle-menu').on('click', function(){
 $('.list-menu').toggleClass('open')
})
$('.btn-toggle-menu').click(function(){.....})

2020-05-11 09:31 UTC, anhnn2401 reviewed
em fix lại menu rồi. a xem lại giúp em với.

2020-05-12 02:06 UTC, sangtx requested changes

2020-05-12 02:06 UTC, txsang commented on src/scripts/script.js
> +});$('.btn-open-menu').on('click', function(){
format, xuống dòng nhìn cho nó đẹp chứ.

2020-05-12 02:06 UTC, txsang commented on src/styles/layout/_header.scss
> +  transform: rotate(45deg);
dùng @include cho CSS3

2020-05-12 07:37 UTC, sangtx approved these changes

2020-05-12 07:37 UTC, merged