feat/footer
anhnn2401/bai-tap_2 pull request #6
Opened 2020-05-07 07:43 UTC by anhnn2401

2020-05-07 08:39 UTC, sangtx submitted a review, later dismissed

2020-05-07 08:39 UTC, txsang commented on src/styles/layout/_footer.scss
> +    flex: none;
@include ở đây

2020-05-07 08:39 UTC, txsang commented on src/styles/layout/_footer.scss
> +.col-3 {
có thể đổi lại . col-md-3 col-sm-6 col-xs-12

2020-05-07 08:39 UTC, txsang commented on src/views/layouts/footer.html
> +    <p>Copyright © 2013 - All Rights Reserved - Domain Name</p>
c dùng biểu tượng HTML

2020-05-07 08:39 UTC, txsang commented on src/views/layouts/footer.html
> +        <p>Email: <span class="email-detail">contact@mydomain.com</span></p>
bất cứ email nào bắt buộc phải dùng thẻ a với href = "mailto:email" 
ví dụ: <a href='mailto:abc@gmail.com'>abc@gmail.com</a>

2020-05-13 07:32 UTC, sangtx requested changes

2020-05-13 07:32 UTC, txsang commented on src/styles/layout/_footer.scss
> +  .title-latest {
dùng last child thay vì class latest này

2020-05-13 08:08 UTC, anhnn2401 commented on src/styles/layout/_footer.scss
> +  .title-latest {
chỗ này tên của nó là latest chứ k phải last child đâu a. phần nội dung của nó là lastest blog nên e dùng chữ đầu làm tên luôn

2020-05-13 08:55 UTC, merged